baseURL: https://thesystemicprogrammer.org
languageCode: en-us
title: The Systemic Programmer
theme: 
  - tsp
  - hugo-cite

menu:
  main:
    - name: Blog
      url: /blog
      weight: 200

    - name: Topics
      url: /topics
      weight: 300

    - name: Pathways
      url: /pathways
      weight: 400

    - name: Tags
      url: /tags
      weight: 500

    - name: Software
      url: /software
      weight: 600

taxonomies:
  topic: topics
  tag: tags
  pathway: pathways

related:
  threshold: 0 
  includeNewer: true
  toLower: false
  indices:
  - name: "topics"
    weight: 150
  - name: "categories"
    weight: 100
  - name: "date"
    weight: 10

heroimage: true

params:
  author: Thomas Berchtold
  authorImage: /images/thomas.webp
  showHero: true
  showHeroForSinglePost: false
  searchSections: ["blog", "software"]
  citations: false


outputFormats:
  Lunr:
    baseName: "index"
    isPlainText: true
    mediaType: "application/json"
    path: api
    notAlternative: true

outputs:
  home: ["HTML","RSS", "Lunr"]
  page: ["HTML", "Lunr"]