baseURL: https://thesystemicprogrammer.org
languageCode: en-us
title: The Systemic Programmer
theme: tsp

menu:
  main:
    - name: Blog
      url: /blog

    - name: Categories
      url: /categories

related:
  threshold: 0 
  includeNewer: true
  toLower: false
  indices:
  - name: "categories"
    weight: 100
  - name: "date"
    weight: 10

params:
  author: Thomas Berchtold
  authorImage: /images/thomas.webp